/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Expenses: () => import('#controllers/expenses_controller'),
  GeneralExpenses: () => import('#controllers/general_expenses_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PointsOfSales: () => import('#controllers/points_of_sales_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Sales: () => import('#controllers/sales_controller'),
  Users: () => import('#controllers/users_controller'),
}
