/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'date', 'id', 'label', 'pointOfSaleId', 'purchaseId', 'saleId', 'type', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare label: string
  @column()
  declare pointOfSaleId: number | null
  @column()
  declare purchaseId: bigint | number | null
  @column()
  declare saleId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GeneralExpenseSchema extends BaseModel {
  static $columns = ['amount', 'category', 'createdAt', 'date', 'id', 'label', 'notes', 'pointOfSaleId', 'updatedAt'] as const
  $columns = GeneralExpenseSchema.$columns
  @column()
  declare amount: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare label: string
  @column()
  declare notes: string | null
  @column()
  declare pointOfSaleId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PointsOfSaleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = PointsOfSaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseSchema extends BaseModel {
  static $columns = ['buyPricePerKg', 'createdAt', 'date', 'id', 'notes', 'pointOfSaleId', 'quantityKg', 'supplier', 'updatedAt'] as const
  $columns = PurchaseSchema.$columns
  @column()
  declare buyPricePerKg: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare notes: string | null
  @column()
  declare pointOfSaleId: number | null
  @column()
  declare quantityKg: string
  @column()
  declare supplier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleAllocationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'purchaseId', 'quantityKg', 'saleId', 'updatedAt'] as const
  $columns = SaleAllocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare purchaseId: bigint | number
  @column()
  declare quantityKg: string
  @column()
  declare saleId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleSchema extends BaseModel {
  static $columns = ['buyer', 'createdAt', 'date', 'id', 'pointOfSaleId', 'purchaseId', 'quantityKg', 'sellPricePerKg', 'updatedAt'] as const
  $columns = SaleSchema.$columns
  @column()
  declare buyer: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare pointOfSaleId: number | null
  @column()
  declare purchaseId: bigint | number | null
  @column()
  declare quantityKg: string
  @column()
  declare sellPricePerKg: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'pointOfSaleId', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare pointOfSaleId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
